spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hibernate:
          format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: info
